homeassistant:
  name: RaspiPool
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  unit_system: imperial
  # customize: !include customize.yaml
  packages: !include_dir_named packages
  internal_url: "http://homeassistant.local:8123"

# Disable default config, selectively enable services needed.
# default_config:

# automation:
# cloud:
# config:
# discovery:
frontend:
  extra_module_url:
    - /local/card-mod/card-mod.js
    - /local/custom-ui/custom-ui.js
history:
input_boolean:
input_datetime:
input_number:
input_select:
input_text:
logbook:
# map:
mobile_app:
# person
# scene
# Script
# sspd:
sun:
system_health:
# updater:
# zeroconf:
# zone

sensor:
  - platform: time_date
    display_options:
      - "time"
      - "date"
  - platform: uptime
    name: "HA Runtime"
  - platform: template
    sensors:
      runtime_mins:
        friendly_name: "Home Assistant Runtime"
        value_template: >
          {{ (((as_timestamp(now()) - as_timestamp(states('sensor.ha_runtime'))) ) /60  ) | int  }}

tts:
  - platform: google_translate
logger:
  default: info
  logs:
    custom_components.atlas_scientific.sensor: debug
    custom_components.scheduler: debug
    homeassistant.components.switch.command_line: debug
    homeassistant.components.homekit: debug
    zeroconf: error
    homeassistant.components.websocket_api.http.connection: error

script: !include scripts.yaml
lovelace:
  mode: yaml
  resources:
    - url: /local/scheduler-card/scheduler-card.js?v=0
      type: module
    - url: /local/kiosk-mode/kiosk-mode.js?v=1.2.1
      type: module
panel_iframe:
  node_red:
    title: Node Red
    icon: mdi:wrench
    url: http://sparkly.local:46836/
panel_custom:
  - name: panel-redirect
    # url_path needs to be unique for each panel_custom config
    url_path: redirect-server-controls
    sidebar_title: Server Controls
    sidebar_icon: mdi:server
    module_url: /local/panel-redirect.js
    config:
      # Where you want to redirect to
      target: /config/server_control
shell_command:
  calibrate: 'python calibrate.py "{{ device }}" "{{ target }}"'
system_log:
  max_entries: 500
