sensor:
#  - platform: template
#    sensors:
#      pool_temp:
#        friendly_name: "Pool Temp."
#        entity_id: sensor.pool_water_temperature
#        value_template: "{{ states('sensor.pool_water_temperature')|float|round(1) }}"
#        # icon_template: mdi:coolant-temperature
#        icon_template: mdi:oil-temperature
#        unit_of_measurement: 'ºC'
#  - platform: onewire
#    names:
#      28-011564d449ff: Pool water
#      28-031504ae5eff: Pool water
#    scan_interval: 31536000

# Atlas Resistance Temperature Detector (RTD)
  - platform: atlas_scientific
# For serial ports use:
#   port: /dev/ttyUSB0
# For I2C enter the hex device id
    port: 0x66
    scan_interval: 300

  - platform: statistics
    name: pool_water_temperature
    entity_id: sensor.ezo_temperature
    max_age:
      minutes: 60

automation:
- alias: temp_lo
  id: '1559049959764'
  initial_state: true
  trigger:
  - platform: numeric_state
    entity_id: sensor.pool_water_temperature
    below: 7
    for:
      hours: 48
  condition: []
  action:
  - data_template:
      message: '{{trigger.to_state.attributes.friendly_name}}: {{trigger.to_state.state}}{{-
        "\n\n" -}}@{{now().strftime("%H:%M")}}[{{now().day}}/{{now().month}}]'
      title: 'temperature low ({{trigger.to_state.state}})!!!'
    service: notify.pushbullet

- alias: temp_high
  id: '1559049959765'
  initial_state: true
  trigger:
  - platform: numeric_state
    entity_id: sensor.pool_water_temperature
    above: 32
    for:
      hours: 48
  condition: []
  action:
  - data_template:
      message: '{{trigger.to_state.attributes.friendly_name}}: {{trigger.to_state.state}}{{-
        "\n\n" -}}@{{now().strftime("%H:%M")}}[{{now().day}}/{{now().month}}]'
      title: 'temperature high ({{trigger.to_state.state}})!!!'
    service: notify.pushbullet

